version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./db.env
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./db.env
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
