version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "8080:8080"
      - "9229:9229" # Für das Debugging
    env_file:
      - ./db.env
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./db.env
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
