version: '3'

services:
  app:
    image: dasultras/splitwise-interest
    restart: unless-stopped
    ports:
      - "3100:80"
    env_file:
      - stack.env

  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      - configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    env_file:
      - stack.env

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "3101:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@db:27017/
    depends_on: [ db ]

volumes:
  data:
  configdb:
