services:
  app:
    image: dasultras/splitwise-interest:latest
    build: .
    restart: unless-stopped
    ports:
      - "3100:80"
    environment:
      - DB_HOST=db
    env_file:
      - stack.env

  cron:
    image: dasultras/curl-cron:latest
    build: ./cron
    restart: unless-stopped
    environment:
      - CURL_HOST=app
    env_file:
      - stack.env
    depends_on: [app]

  db:
    image: mongo
    restart: unless-stopped
    # ports:
    #   - "27017:27017"
    volumes:
      - data:/data/db
      - configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    env_file:
      - stack.env

  mongo-express:
    image: mongo-express
    ports:
      - "3101:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@db:27017/
    depends_on: [db]

volumes:
  data:
  configdb:
