version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20 

    volumes:
      - ../:/workspaces
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig

    environment:
      - TZ=Europe/Berlin
      - DB_HOST=mongo
      - DB_NAME=app
    env_file:
      - .env

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  cron:
    build:
      context: ../cron
    image: dasultras/curl-cron:latest
    restart: unless-stopped
    environment:
      - CURL_HOST=app
      - CURL_PORT=80
    env_file:
      - .env
    depends_on: [ app ]
    
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data
      - ../db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
    depends_on: [ mongo ]

volumes:
  db:
