services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  dev:
    # See version: https://mcr.microsoft.com/v2/vscode/devcontainers/javascript-node/tags/list
    image: mcr.microsoft.com/devcontainers/typescript-node:1.1.9-22-bookworm
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
    command: sleep infinity
    env_file:
      - .env
    profiles:
      - devcontainer

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  cron:
    build:
      context: ../cron
    image: dasultras/splitwise-interest-cron:latest
    restart: unless-stopped
    environment:
      - CURL_HOST=host.docker.internal
      - CURL_PORT=3000
    env_file:
      - .env
    profiles:
      - test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  test:
    image: dasultras/splitwise-interest:latest
    build: ..
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
      - PORT=3000
    env_file:
      - .env
    profiles:
      - test

volumes:
  db:
  configdb:
