name: Docker Image CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches: [$default-branch]

jobs:
  docker-build:
    name: Docker Build & Push - ${{ matrix.tags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: "."
            tags: ${{ github.repository }}
          - context: "cron"
            tags: ${{ github.repository }}-cron

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ matrix.tags }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image ${{ matrix.tags }}:${{ github.ref_name }}
        uses: docker/build-push-action@v6.16.0
        with:
          no-cache: true
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
