name: Docker Image CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches: [$default-branch]

jobs:
  docker-build:
    name: Docker Build & Push - ${{ matrix.tags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: "."
            tags: ${{ github.repository }}
          - context: "cron"
            tags: ${{ github.repository }}/cron
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
